// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "FilippoBrowserPlaygrounds",
    platforms: [
        .iOS("15.0")
    ],
    products: [
        .iOSApplication(
            name: "FilippoBrowserPlaygrounds",
            targets: ["AppModule"],
            bundleIdentifier: "claudi.filippo.FilippoBrowserPlaygrounds",
            teamIdentifier: "974TR9G2UN",
            displayVersion: "3.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(path: "../FBrowserPackage"),
        .package(url: "https://github.com/FLEXTool/FLEX.git", .branch("wip/spm"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "FBrowserPackage", package: "FBrowserPackage"),
                .product(name: "FLEX", package: "flex")
            ],
            path: "."
        )
    ]
)